apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt
    namespace: home
type: Opaque
stringData:
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:XsZ3YEwWwUTKCQ4=,iv:M0xNL7jI30xaRwv+oAmR1JKt2HSTQSrp90QGXxEEH+Q=,tag:/951ZgJXgo0IXpyGO+CfCg==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:aOPe7x3shikG,iv:u3fb3xpD8C3eKmbu1sQLtzG8GNqBD8oFIV9Grj76ujA=,tag:r3e4qPshauHu1GaHmqujAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MlpDaGc3ZkZRR3RRVFo4
            bnE0QTRlOWQxYlY2K1lxOEFteGJOeTB6UmxRCnhwS1Q0WHlBOFMvRWRDYVAvck9y
            eDVKVjJlWkttSldGVFlLbFl4ek9RR2MKLS0tIFpqZXZESWNXbWkyZlUzQ0pVb1Q5
            N1BYa20vc0NmOGI4SDdwZ3hNUU5uQjQKH2V6Wci6a3bZ0wnXY30gFToUsXEMeDWl
            KKmlIRuz6vR4/TzNMlCE2sVOfYLqyloOZn5aGrhWSpBF/iE4UCpNIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T08:17:17Z"
    mac: ENC[AES256_GCM,data:acqRhdaMjte0Wf4i1QwdMlRYKwfdyOoIye+nyzxwp+KfQfBNXJC2GfW2rRTd8ar/9Jann06C2WRl0Y//SdRFnYHQdAXcbbgW2dIMtquTeW2TAI0pzVrCamcT3Pfw3REr0L4qAmltzsUQ8n6tp+TEb548hxHvw15o+ulAo/H6C5c=,iv:wNiNW0bGZgGUbhkit9aXqy8u8qxGenu+Gz/SLnOQvfU=,tag:R0YGVMfZXKzhvNfHmb/n1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
