apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt
    namespace: home
type: Opaque
stringData:
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:pw6Y5C2gbmrkTCE=,iv:SVM6R/zTGr9PDWXs9rC9VrLeqJLLkMwYh0NrulRsjT0=,tag:A/iux1AR9lq4i7c2sm3pOA==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:Qj5gmR8DNlbm,iv:dA7TpXF20SvctwdhyaAEfEvdoKbNSmkQ5bFB+02b3yA=,tag:9gNCFembTPycyd63unU/Og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb2NHUUVRdHV4ZnlYV3gw
            eXVDYnhxQlVHNnpGakViM2pHY0VTZDVNMkg0CnByaDZSRGllT2tGeVVsQ1d1RXpN
            YlZqc1Joa2hzUUhMQ2dhY2RmeWwxd3MKLS0tIGd1Y1BPOWJSWVMxSGdnOElUV3ps
            d2M2dHh5TGNvbnJWY29qSXFld0w1RXMKolqrkAw4dpNSS3lI7rsWvkP2oLT1ak7/
            lyDbjb5emqHjTw2pmzbYljpGgToVu3iLCSNt8CgWOFI3hh19BkWweA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T08:50:50Z"
    mac: ENC[AES256_GCM,data:sIjjfW4C5CMsIXAmp4KXcg9z786vejgnZWm7jPlJDE+2Fev+0S3AE58B3gZMg5DIzZt4Jk22kLF27FTZELqElTCSJEjQEHCXq4KpymyhmEHvWAwM6POfxaiJW6tHMAgDkfSgro+kQQJxxqFaiz7Tj6jOfSXVzhdP3uH3+W23k6U=,iv:rrNOv2vs9KpSrib18NIfXd8mp9W6kwfBvxWZKyZH5tY=,tag:OGMgu2Quu03qr0wJxoRy1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
