apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt
    namespace: home
type: Opaque
stringData:
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:UlChZ5fTbTu6g6E=,iv:MAI4WKYtj13bhjNxVwueVpE1eG9BdOlIWmE1LAv35F4=,tag:GAmt7b4EwAG9yH9vmml2Vg==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:M3WcRFCzjmEz,iv:F1EvPewI6Sdboz/XoXkSo4XWXyu5aCmJFfR1kyZOBHQ=,tag:/LL25jO+ETnvBsVPisTGbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRVN0bnQycllzTGdxM1Rm
            NGo0TUdyZThpVzNSNUxTdTY5aWtCTmpHM2xRCkdjekFhVHhIZ01ZWGpyTkdsUURa
            MDl6WXEwUHZlVDRncnRzQnFnUnEwT0EKLS0tICtvSGlXQVFFSnJxbk5oUzVaekZn
            NU1YblNrWE1HV1Z4cG9jMjJjTG91TkEK8AxsjkuILa34Xxmpt5DXxJB7p7wEj9f8
            MlcNYyWvCw8Ojd3mBheJ1f3AtnCC8z/zv18OYeujvDw5A1RPyzmRIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T09:42:00Z"
    mac: ENC[AES256_GCM,data:hru/tq/7Dul3yOLeYW4VPhxVFD09OIFLeU1/GlYUXSv5XpS5Hl3JqwgkOqbtlAlLV/uvFNTymOXswRvejMIY/WLsxUBiU2IabH4/50/MF+F/FA+0FA7AXsKLs0TTqZkgbcVLufx2vZJHU3VeqNLWAoWKWTSckVyPVmDoB0P2/cM=,iv:l40iO6X6/AQtXLnS37FBjNs3s+ws3crhJ2bmLkaiYAA=,tag:Hc5qh8QY6wy2Y4f9WZUohQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
