---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn-charts
  namespace: flux-system
spec:
  interval: 30m
  #url: https://charts.longhorn.io
  url: https://marcomihaicondrache.github.io/longhorn-chart/
  timeout: 3m
