apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
type: Opaque
data:
    tunnel.json: ENC[AES256_GCM,data:nv61zDvOtnQN0M3EbZMHsojLAGWE7Uphr2TGLzDQiJZO9xNr7LIVqxIFOO/UlqluqcWG9Gw/ohq41DCGNxLBRICqCs4I53ckIAV5FsEpfpOWIVSlzdlNT2QiEiY0IzZoYNK4AtN/cbbf7esd58zulpCEsl66Ywea9bkBUpXolyr/Un4JtrmZEaDtF7rcbzPmOTp6JaHzrDVOffkVHBRyBoV5jM4VZQEAGqwsl7bO5C4QdcYFnXnLhUXgHPiPfTFfy2Tj25Wx5CWvkpTnKZeCoT7I6U+h1rca,iv:/Pff9Frq1w3Gu/QRBKVDmSFIEZNtn4mDq97caZm8RZs=,tag:KqfbpBCcZWGMpGadXgvnwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjclk4eU92SGlsbnRQNVZX
            SlFJSk02WlA5Ujg4R25zSVdmNktrRm5FQVJBCjBqSU1QVEtjNnBWZ3Jweitzc0lw
            VDF6S24vbTZ5RDlwMkpRc3pTa3VoTFUKLS0tIGIzZXZUR0VDaEdxb0tlblIwY1Vw
            SHl1RFRLMEVVSDRRMVEzQ2d5cHdTMGsKHKAVmSfB/0EbvoXFpCTrbiktN57v0mre
            2xxAeBnST5MqJ6AMzU3AiLmAfnVZXExq7q36RjouvB4iXzm3a63Zuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T09:44:59Z"
    mac: ENC[AES256_GCM,data:Q/fItSIOaRCTGqFyDakM/wtrGWk+eIoj8KTnlPi9eHhglsqC/AyJsFTQO05kz3nnc+gZ+0nCDeOokiGHszwE30TcBcjtwGaM8EkpNTyVWgFFvFLV3xPa9XFaTO6abcc7bz/M6Okz0D9U7UNygXF9O/dJrQoqOD9Pl7rgFuemkX8=,iv:ujtfXyv/XEtFyZK293T27nneesGfgPSTNcR5GrPXZ/0=,tag:Sf6fdac3XnUnQo1o5GgPGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
