---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: emqx
      namespace: home
    #- name: stackgres-operator
    #  namespace: databases
    - name: longhorn
      namespace: longhorn-system
  values:
    image:
      repository: ghcr.io/onedr0p/home-assistant
    env:
      TZ: "${TIMEZONE}"
      #POSTGRES_HOST: postgres-rw.default.svc.cluster.local
      #POSTGRES_DB: home_assistant
    #envFrom:
    #  - secretRef:
    #      name: *app
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SVC_HOME_ASSISTANT_LB_IP}
        ports:
          http:
            port: 8123
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
