---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: emqx
      namespace: home
    - name: longhorn
      namespace: longhorn-system
  values:
    tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        # Evict pods from the node if the node becomes unreachable after this toleration timer expires.
        tolerationSeconds: 15
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.12.7
    env:
      TZ: "${TIMEZONE}"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SVC_HOME_ASSISTANT_LB_IP}
        ports:
          http:
            port: 8123
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.9.1
        # git:
        #   deployKeySecret: code-server
        workingDir: "/config"
        service:
          enabled: true
          type: ClusterIP
          loadBalancerIP: ${SVC_HOME_ASSISTANT_CODE_LB_IP}
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        volumeMounts:
          - name: config
            mountPath: /config
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi
