apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: velero-s3-creds
    namespace: velero
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:mo1tu79Qbt5hHyBP4EAv33HVs4g=,iv:5hxfVOh0949iG3qs42GzAFIGQhrE8uMSQkkQ2k+CNeY=,tag:g5+ShgO5pQK0ANCJvdVfCw==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:2AT+3OHtKRnujN6JY++Rd1/B//4iWt6IZbWVHU3zmRwOLJXmiThdXNreXg==,iv:KiYWkAnVzrGSSqeLiLynmV+CCu5Xf0fmLDhVoaOkapI=,tag:Z5JkPgvPwVzqhcQdzIkgmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM2Z1d003MWUvV2Fucmxp
            YkE2TmpvaGZWVkI1Mmhkc0hmMXc5cExkQjJrCkk5OStvdXI0dEpaeDBSTnlSWFJw
            a1lQQUZhNlU0Uk1YbkZISXdpaEZ5c00KLS0tIDRpWTV1eGlqQkZzSlZuUHJ0Q2xa
            Y1czRlV5T3htQkVEMnl3RnVPdS82SDAK2Oqp/t8o42iwuJ43trsLz8h9wT4qVi4r
            UkrtlvIGX6QfTQK5VAL0W0cMgcS2vnx0QPVQ6tGNj0dGkwbBCZL4Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T12:37:09Z"
    mac: ENC[AES256_GCM,data:Z0ASjPMzPy7+HP8SXNwcDr2wtbLEfbb6KSFvirYonEHjHBCncpWCvC6erYDkPQ1vOfaTGu6o730Ly0dVX7m4ze4kgfHZ5O9SVXWICHC4vgxU2/vNJPVY+T55O/yA4U8/Bj7nI5kUyNWyaipZJAeXgscU2EgqJUwfXdTgL66kaAo=,iv:w1iR0UhuCgpB0H9ckZmzCt+IPuOMQehSm2rxhT8sRjI=,tag:2bzLG3nkhyWRGVfC6ZiIWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
