# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:rEMp2LXYblzCeDcs+GW4AHX4vi6sO3ekFeyVZR0=,iv:CFeDFdKLuK1gJqzLYULyygnmwd2s/SCGdoVkixfqDRQ=,tag:pah5ibTJzu85gy+zMaW4zQ==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:1snq/+sTTWTqsymDaBksY2xXiGA9k1b4q1YMD/iUpmKPNJdVqQ==,iv:eZS6aEKcKYAiVzDP4KfNY27qPjs9JUUp1P7EvpXvMRA=,tag:5AdTvw0pg6dWcydRuG/Vng==,type:str]
    SECRET_CLUSTER_DOMAIN: ENC[AES256_GCM,data:d/vNKSStCdByteHzTOgivJfsfagPC5yKaqoF,iv:XgRA+EGm58Z7bmlcOPImBypmHfu0Rxs3cBZ7O60qKtk=,tag:wmk3HKs3enBO0DUrslT4ZQ==,type:str]
    SECRET_CLUSTER_SELECTOR: ENC[AES256_GCM,data:gPaLpKwFQIDSfaGy8cjL47Rk4HjBwC7z7xF2xVg=,iv:Bx97GF5FQU3clscsj8rFx3tw9B4Mjp5hstGkWPIhQsQ=,tag:jUdH3I/yk7Dj51ahw00L8Q==,type:str]
    SECRET_CLUSTER_CD_TUNNEL_ID: ENC[AES256_GCM,data:l3t5fEIr/T4OKxNj6BJhKjvmO97vGHnb9R0lRJxniqdWSRnB,iv:IXNrkHLtFa4top3OwcoTgrchLk+iSSTPjiyc43D5zkY=,tag:PlGa5kzSQF8ec6NIp88Yqg==,type:str]
    SECRET_CLUSTER_CD_TUNNEL_TOKEN: ENC[AES256_GCM,data:OfL/eUY1d4iF6YhE168s7bZv29fxctLGQ1sbyFXjlfNgzlHQag7Qqv9mrRE7lvzZnTavJo5yOxNZFHUkCzieFO/MnFZzvFuHwHWU1lPe2jUrtfGgKWfXgXwSbatBht8kMLuWYMYO+Tb8352vH7pQA0mA5qnl8vbCBKBLIaCMtSYxOOupxyWhWDjszppOXk45viq86xuZSjyPVyP3kxt69k8E+/QaTLdEd1Gh4AkQBoSPxPCudCoJ1jcpi//u7A+p7Wqlx5K0ylRUo07pErEnfD/iiST7w0ny,iv:wOs/i1MIsyYe0UlqlcHX6KZF0tuRfl21PA5I47y+hiw=,tag:32AYYMVr0LcNk6oer1nhyw==,type:str]
    SECRET_SVC_ZIGBEE2MQTT_USER: ENC[AES256_GCM,data:WyXK7C5Klnj9z3c=,iv:Ulh+rGC7z6IyTMxf/vX2LGZFbmBf0M4ezE3JCp0RBFE=,tag:rx9KWHdYcoItEcgMrwuVAA==,type:str]
    SECRET_SVC_ZIGBEE2MQTT_PASSWORD: ENC[AES256_GCM,data:6wm5jfOChHnz,iv:VsVeKWb7ixerlpYGoOfASSBZc2yx5q9sdAaT8n3LtWQ=,tag:ehvzbgjcAJHY1kvS6TO9fA==,type:str]
    SECRET_SVC_POSTGRES_UI_USER: null
    SECRET_SVC_POSTGRES_UI_PASSWORD: null
    SECRET_SVC_EMQX_DASHBOARD_USER: ENC[AES256_GCM,data:2c+54Ec=,iv:lV/kg68IlmUyzyNoLorTdRfP+AX5+JzeA+y3mELi1Zw=,tag:COlR+ABe+SpdB1BNzZRpBw==,type:str]
    SECRET_SVC_EMQX_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:w3Y4lUNSAk89,iv:vfgKNZV1TcEsmiyVGszyrNHe9PuTrz61D3ROHwFDmmI=,tag:oZv009cv5CUwzTtLugGbEg==,type:str]
    SECRET_SVC_LONGHORN_BACKUP_TARGET: ENC[AES256_GCM,data:fm3RJgUQ+XZY9xoPP5wCo1TUk24=,iv:Yvaxt4L/kc/Z64oE4kgPCOp0QwjYZe1gTRPCXPV8/Gg=,tag:UQ/rsGuFy1wCmWVUw3+JIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bkQ1YVVEWmthMHFTTzU1
            ZWtHN2R5RElQa0pLU0FkVWJiTzBJOEFxOVZZCms2TDF4L1VraTkrUlBGbHJ5VEZ3
            RHh5WUI3V0c3dCszdjFNdEZzS2haS00KLS0tIGRZMXUwcUVKREY0U1VWZ2dJM0pv
            eVdFak91NnFMNTh0ZHlER1RFNGhlUU0KixTZ/9TpTSi0llmKvkj+abR7haXelirT
            8ISAL42GmVuImbCMhDevyFYa3OaE7INR3Wxha0yluWQggsDryeEulw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T09:37:18Z"
    mac: ENC[AES256_GCM,data:/f9tByxCJdxGL5lfw+1J+7ZJ1sKMRhZWDoz/2AZqXSgT2b1vRalg+nr+nFMwxV1CPgdJgxyh8XC4ZX5QkUwTINrQnv+jp7SeenHZNKCOdPvWy9FI+YxkfKc3lBVfDAf7FTFk7baU+Nh09MIV6cI0XbPQPbCjX79Pq0F0pZU+Usg=,iv:JYN2jAGBa2h4tW3MdFQhWbLoxb4Es25dG1HIcb3ePYc=,tag:HyjtDz2JmmeF4ysuWzR2qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
