# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Pv7gbC+U/nKurbvsmx9rYOxzT19CoUlbJbDDslM=,iv:lTg3RNjVykn4uaJ5OmWrvjUIWxovSdxCq22dT6sQDVM=,tag:DuesRdq1L6bUdwLwYsiyNg==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:vseJ/IkmkOhGgMyd02kpNEvd6A0Uo5Iqc1YGRtrOGeVIiqbM7A==,iv:xpcd8iY46e04qT75V3mFNql8RwC7qPFIhJ/lHFFcEhQ=,tag:j3Tznr0gtlMVZH4NaCoUkw==,type:str]
    SECRET_CLUSTER_DOMAIN: ENC[AES256_GCM,data:EhYCKIL9XFXV0n5VwRsUwv1b/0Q5SYRvVihs,iv:Ha08O0axvjk1eke8M5dcBo3bU2vHP0ALQ0IsTYTCY2s=,tag:ceM0IqWLLVwJxZTRQ4mnvg==,type:str]
    SECRET_CLUSTER_SELECTOR: ENC[AES256_GCM,data:gvfVCXPasJWVFvsju8+GxBZ2bUPNd5F5+D3ksA4=,iv:8Sc+sw4n5ZOB971DAPC8eOwOYWHs36gi9n4j77UCHU8=,tag:bQzbXZxZZGateal+7h7Y3g==,type:str]
    SECRET_CLUSTER_CD_TUNNEL_ID: ENC[AES256_GCM,data:dkwSsIDYUhOKt7A4cBEI82xNjJn77UrcPD/za2hHfh5HQLpF,iv:Qr/dGHWcQkZEAmvoIiSmz8K5f3W8fU35UgnvEjLsK6Q=,tag:8U0HihlQP6wzv0udPDS/aw==,type:str]
    SECRET_CLUSTER_CD_TUNNEL_TOKEN: ENC[AES256_GCM,data:mgevkUvNaJ7A3SexgZYz+Z2HJQDHOIr3NUHG1s3oGD45n4vSHxIkUbZ51KMOVp8DdkaZzbYcRJ7oYbv/Sk4H7QRYso1zCdm2mieAsd+/xUNXsAA9hrlUMrXXDODoctccGlMYzVpp3GgJVofbJMxezSa5y5n3lbk1J8kIqRdUhwfdGdGHEYewYkppBj9TplcmnZLPl2KjkI+9ZRQ/sG3pVCD3oddWVDSmpzKhx7d+OZ+Xh8M1oZYDpHeTmmuAnTdEad7vxBXp99hFdqmeMjmbRRxee66rBEPI,iv:fJaI9tt0yfL76VxemySrZ7LbPMZINS4nP/8o0Urm7ho=,tag:IaeAbPnqY3+cRp8gz4Y2bQ==,type:str]
    SECRET_SVC_ZIGBEE2MQTT_USER: ENC[AES256_GCM,data:N2C6RpV4RVNeDrQ=,iv:N7I3cNroSnHJfS4YJz2XWWocnmbgDY0feIbMlhRWrBk=,tag:iVv3Nl3BfOWDxlCroeMbpw==,type:str]
    SECRET_SVC_ZIGBEE2MQTT_PASSWORD: ENC[AES256_GCM,data:Zpvhh1BA9NWP,iv:NnjhmX3cNW6xinp/xFTlKLFvLuEaLgV+215VDHKkK8w=,tag:MJrGiC1wY/qaQmbhzwLQaw==,type:str]
    SECRET_SVC_POSTGRES_UI_USER: null
    SECRET_SVC_POSTGRES_UI_PASSWORD: null
    SECRET_SVC_EMQX_DASHBOARD_USER: ENC[AES256_GCM,data:wPaEbtM=,iv:GU4Kazm7Zr4cie7aD3YT8KyLlNZel7bH1Wt8ZVKXL0Y=,tag:r7Gw2UlPoQTeiWMW+odZ7Q==,type:str]
    SECRET_SVC_EMQX_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:MzukuGXD9mza,iv:zlawKhivrseWveQ9BnGWt9BqIFxSIsEpFpR/7JvLdWU=,tag:8lgBGWoWevaWfrvS9d7OBA==,type:str]
    SECRET_SVC_LONGHORN_BACKUP_TARGET: ENC[AES256_GCM,data:m+foVEm4plx7ZsOI9SNlnUrKQng=,iv:CNpSKLILWrqMowjXlv4Wn3VdHcUauQ/nS6YJ7SZ2WqU=,tag:2n5cvMpRYJNUQX25kq/Vyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdWVpQnlKNnBreTQ2T1BY
            OGcwV2FSMDFaLzEvalNUSVhhRW5MOG9nSnpnCjdIcmc1L1hnOGpLeW5kTTl5WGlB
            VDFYMlcyaXZvNDJPUVdLMzhXNld3TVUKLS0tIGowcW9Jb3I0WnZHMkpUL0NKVWtx
            V1dZcXMwbjZEaGxjQkIwaEh0VlJmUE0Kt6Ns7Vh6ee/urjXWicWdX+6dOA9Ey8Wh
            Cu5FMslDzCkDchAfNsNtRH2dKUmKSW6+690+XgEuFrhl+WPlauMBVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T09:42:00Z"
    mac: ENC[AES256_GCM,data:6mHt8F+Dq2earcel7+GbHKvhakDGRaN7U+ImCla/g0Ocyednof65HFF2S3YUOHTpsWoWSsVpYX+wpJJPqhzhcsceFH+uwyrZqg4WE62VrRKlLwu9dTv5a3wJXdRnE43j5C5Aw4S1es7kl4GqBilLHUzlv1AxIz5sjWRSvLddRMM=,iv:9ckLO6pcq+fTt0MZ6SmlWQ7gEPw4W6AXSZ3xPORrlBY=,tag:fDekXDH7TkwCmlbjTse1BA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
