kind: Secret
ansible_user: ENC[AES256_GCM,data:+3n/8w==,iv:OcZInjyu+WQQZr8MQ8cAOplGs4EL7LSnr2l8hbqx2r4=,tag:ZrG1Jyz2UotxKISLqPs3vw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:NKPlnTcNPYk=,iv:duNtqw/gPRh0oc7uk+0cuqEEtT68hLMfLGw6AxGITQA=,tag:TykGiLoCTDrjT/inOb1bnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVEN4T1pwTnVyYy9nYTc0
            K3pXdXFTWGlwdE9xRUJvdWZHQWRkWmEyU2pRCjRuZmhPeS9ONzlPNzNrN2VFM1gw
            aEFueHU3cnpNdFFaYTMxKzk0UFlRN3cKLS0tIE5wY0JvYVFkTGc5aVIvZjlVc2tD
            d3ZQM1lIS3AwS0lxd29iL3BGV3NqdW8K9rdDYF6JOr2P+0p07taFPpp3j3sPYhj9
            /9FFa/ROQgwftVz38KjcRAnuMSa2zBPn2B+6mEDU5ovUST6ILnF51w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T08:58:17Z"
    mac: ENC[AES256_GCM,data:v9iX7fAroIAYFHLwrPe1pqoptiFOoYGYiRZsDctfpEYfNP7hIzGzqgW9pZugctUNuPPfV+pJG8yl37OE9Vef2YaVBh/SBQpBeL+SJNOUB+LRCguPxRh8Pnvbct9cVhM8dx9lOT2cq6rgvW9BtdPjtJrTgiX7sdJ9jCgvT4Ozj9k=,iv:nfvLck/L7YRh+0F+zBPAf5HGTUudmcmeg3dOY/i1yW8=,tag:seVKiE3MFBef+8acHrB8oQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
