kind: Secret
ansible_user: ENC[AES256_GCM,data:PR9y4w==,iv:aV7POPipHIgn75XSONivIUh4E+wTp4dO0YlLAPtmHjY=,tag:j2Q+LG/1WV0XcHTS+tHFNQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:pZZ4zhag,iv:SCNtZuXduSoIAppJ5G3RhmdhbdClA8QF/mSwVSNtJG4=,tag:LkGIYewLczCrbCHQ5NCz4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMGphdHVMRkVzV0VvbUpu
            K2VMQW9LUEFvZ3d5NVJGYTZUSzFpZURxVDNvCjNQWnliMmlHaHJ5eHltV3JxcHVo
            VzZaNm96Z3RqWTVDaW5MZFZpemtySEEKLS0tIHBiMEZLS0Q0SGt2T0hHZUFteS9v
            WG5RZlVUNUJkbDljYmhybDgwSjIrY2cKRMrbHb1aYZ3pKmoD2fAKVmQCxo1VgkKV
            fd6ewtVDzjTaNcfVLf/QvB0iKxiQkOvQtqWOm3sF6kGx0iVZ7BeJSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T09:44:59Z"
    mac: ENC[AES256_GCM,data:bK/Ur6LyXpmMEvm0/eeyiwU9ADwZUbahOYY/SQS++qkUGfz9mxVSU93qkquPIGWCT9+fUK5jLU6Yp9ltPoc6nUMIAYmF3QByN4lFzx5fml6oQ3ckAO+wZG4c5Cm+RgWi/J3tBNUVHIEHWLLeZxGKCJy5t73KzEpNxQzC/MHH9ns=,iv:/3qBd60v9VueTUJW6cJrihQftUcGtstbZK2YKtMBaQQ=,tag:+P5WM0OMCnbBCVnK8NkA+A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
