kind: Secret
ansible_user: ENC[AES256_GCM,data:eKSBbA==,iv:+s3m7YzTmu6XLOkxS1AsPjOF9FKljqiX3Yul6vlt/XA=,tag:uTu2LQdF761wWebQrRH3sw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:GAMs50zFlDs=,iv:H4cBR4sUIE2X6dxaFMzcMRfJpLP1jS0/4akwz+AjUeo=,tag:rvHAj89SWrGvGHKp4zkTOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc3BVTmMwSnRCVlVsQWo4
            VEhNZkpoYjhBdExCbUpWeEptWk1WVXlCYWxBCjhITm9WQ0FDSEx3dk1tVTN5REY1
            d1VwQnhKYW1sL0dUQ042NjFQMk5acjQKLS0tIGx2ZzRWd0ZOcUVCZFJaYTZGRE5k
            Z0lRaGNlUS9wTGNrMTlGTnRtbUhpY0kK5SkKRN1Y0inyYgH5AFb4h+BDpKa3r2t9
            Br/tF/Rlyjr/gW2XfSG/UQQfPr/GSmXQxzF0ayK9r15OVs7Jk9d5ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T08:50:50Z"
    mac: ENC[AES256_GCM,data:rsLoEwcF0/veHzelR3f5QBcGTXejBmDhymQI33VeehpEZWQpqi+ESycmZctVNqSLgIdtVYttgFk41rXDWto1N5gHBN9q+CDReFAlkvjHQ3ZewLaAY39yEje326WhATvhqWAKjDfZfsju2V2ZJGA0xa4LoRZIGltnivgcuOV7zlQ=,iv:Of6g28WWMyeYwKmcC9GksVMbc6JDh5o3SUMa5RZvVB4=,tag:MWINALPghp+JfWXkGOXjTQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
