# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_CLOUDFLARE_EMAIL: ${BOOTSTRAP_CLOUDFLARE_EMAIL}
  SECRET_CLOUDFLARE_TOKEN: ${BOOTSTRAP_CLOUDFLARE_APIKEY}
  SECRET_CLUSTER_DOMAIN: ${BOOTSTRAP_CLUSTER_DOMAIN}
  SECRET_CLUSTER_SELECTOR: ${BOOTSTRAP_CLUSTER_SELECTOR}
  SECRET_CLUSTER_CD_TUNNEL_ID: ${BOOTSTRAP_CLUSTER_CD_TUNNEL_ID}
  SECRET_CLUSTER_CD_TUNNEL_TOKEN: ${BOOTSTRAP_CLUSTER_CD_TUNNEL_TOKEN}
  SECRET_SVC_ZIGBEE2MQTT_USER: ${SVC_ZIGBEE2MQTT_USER}
  SECRET_SVC_ZIGBEE2MQTT_PASSWORD: ${SVC_ZIGBEE2MQTT_PASSWORD}
  SECRET_SVC_POSTGRES_UI_USER: ${SVC_POSTGRES_UI_USER}
  SECRET_SVC_POSTGRES_UI_PASSWORD: ${SVC_POSTGRES_UI_PASSWORD}
  SECRET_SVC_EMQX_DASHBOARD_USER: ${SVC_EMQX_DASHBOARD_USER}
  SECRET_SVC_EMQX_DASHBOARD_PASSWORD: ${SVC_EMQX_DASHBOARD_PASSWORD}
  SECRET_SVC_LONGHORN_BACKUP_TARGET: ${SVC_LONGHORN_BACKUP_TARGET}
