---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  dependsOn:
    - name: node-feature-discovery
      namespace: node-feature-discovery
  values:
    controller:
      priorityClassName: "system-node-critical"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      resources:
        limits:
          cpu: 250m
          memory: 250Mi
    speaker:
      priorityClassName: "system-node-critical"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      resources:
        limits:
          cpu: 250m
          memory: 250Mi
