apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secrets
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dLueAkCJVRJ2FHFtuWKjU189PQ8=,iv:lfLM+wfzVCzqOWSRoguIDTx5kYpe5DZEZ+L9xQf8tlc=,tag:IBtovI7YTqxsO479mt6i1Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Hivb9sJQtny1Ax7DZ7OCjf7NfwGmgZUonaIfUorDHXv6RIiqfvUm7E73FA==,iv:pIx/Auj5KOOoTX+BA3XvCTeuiLxC5SvkpBKtO8ldU1A=,tag:MoHdZCDMXc7j511m77iGJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWXpRbkRMb0FkaDAxRFFj
            RDA3N0tOcVNXcUdCNGNBQWtqM2d1NmF2M1dBCjhHamMrdE4zVDhKNS8wSHh0SSsv
            cm5HRHU3NUc2MlVDdERpYll0bWx6NjAKLS0tIGhoQURpUmpxSk4xSEVGSjZ6cysv
            NHRURXdSTnRIMko0OHZlMWgxbHp1d2sKG6QY9o9+yIfEyNJHgjWaqxZx1wpF9ChE
            g62/ry2FXDdG0t3ZPMQBZuADPy6DIhVIkzekzlMrA1VrftapdqA+Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T08:18:34Z"
    mac: ENC[AES256_GCM,data:dHNbZ3t0NSWqtiHZCNVAcocmqVnIieffP7mNAG8Ja7hgrVHe43IZXRM1BQWm+ADVtXQVPvrZjzziz1euXbxhN8mTcgxw9YGRZlVnziZCud3JzyrzIml3OyOGVL3wa+fd1fDovpXK5AdoddPoXpALUIR0ZvRKIGssTy2LPHO5pLY=,iv:Ht40FcILw45c1KXy4GNp+e9dzgkgK7w/Vh1tCstwvak=,tag:xDyv40Izfn1jMZANWBnneA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
