apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secrets
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RWbFI9AM7aeEGOM/yDbFhFH+5yU=,iv:FF0YaI6h0oRg2rA88/2VNbt5u+HKvu+FXZlxxA0nuZc=,tag:9xWDWV7NiKI73dyfuiimzQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Yr2jc+d+SDbhAjf+qWlhLtYsA8tmLS/ulWFJHXqdCLFQDVHj5Ii+SQ==,iv:oBPT0deLknJomnFicurFKu2GQ8g49fpbycof4DuqioI=,tag:5i8F5LktEU+ucSUzjTfg7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWXpRbkRMb0FkaDAxRFFj
            RDA3N0tOcVNXcUdCNGNBQWtqM2d1NmF2M1dBCjhHamMrdE4zVDhKNS8wSHh0SSsv
            cm5HRHU3NUc2MlVDdERpYll0bWx6NjAKLS0tIGhoQURpUmpxSk4xSEVGSjZ6cysv
            NHRURXdSTnRIMko0OHZlMWgxbHp1d2sKG6QY9o9+yIfEyNJHgjWaqxZx1wpF9ChE
            g62/ry2FXDdG0t3ZPMQBZuADPy6DIhVIkzekzlMrA1VrftapdqA+Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T08:38:06Z"
    mac: ENC[AES256_GCM,data:9xcghnf0iXqKpX8EHHO/fkcXczaUOaRTEYu9S3cDVBnoJSdG2WhaPhl88sC0dMFqL2xEJDuQnHKuGnh5ojtSIYLVG6WU4drZKXwTUNcxLl0o/gJBwxr0acEB5Zz3Zl7v4DLoROKNXdky9snhiPTBUN1S3bsMQGpffDe55Ki80EM=,iv:InZxvdUbQI6ouc9AjAMc69RkjbG+jqwwMYxqkRtt3Jc=,tag:0CeGS9sgC/I/wwfCQ7G3Ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
