apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secrets
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:A1RPLG2hp1JyFhEKrdYF+zMEWnM=,iv:MtSWbEnZAcYzq3JoUKe+Kd7MpK7i3YcQEkUUP8kcGBA=,tag:NCcmU0hREoRtt9kJTLI9XA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6HS8Pn/6L+aMGPYA0LX2hYHf+EG4dpQHcEUeMkTxG8KI6Y3kCEwKQg==,iv:Ma2iuPYNcTQqSGL+5bZY2Kxr08YHZTwxY15ImDk36kM=,tag:I5dE1Wfb/7gbxGg5Wz1KXg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:i40IHhmGCQ5pew==,iv:zjdB/zVKRkncNUUmp/vkc/PgVY0P2ksmuAtXWlpMZWQ=,tag:RciVzfGYpYnu3sSJm/BbxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWXpRbkRMb0FkaDAxRFFj
            RDA3N0tOcVNXcUdCNGNBQWtqM2d1NmF2M1dBCjhHamMrdE4zVDhKNS8wSHh0SSsv
            cm5HRHU3NUc2MlVDdERpYll0bWx6NjAKLS0tIGhoQURpUmpxSk4xSEVGSjZ6cysv
            NHRURXdSTnRIMko0OHZlMWgxbHp1d2sKG6QY9o9+yIfEyNJHgjWaqxZx1wpF9ChE
            g62/ry2FXDdG0t3ZPMQBZuADPy6DIhVIkzekzlMrA1VrftapdqA+Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T08:54:56Z"
    mac: ENC[AES256_GCM,data:Ud4+oPRjq71a0HYDAbeD2SVityXRQh+iKZm2vvV5XsfeJ6il1Afqj9lZrcVCFVwYX1zCDCAzc2YwilKaq1SP23kBz2GSXgIP9vzjMLBXnMKx1v+LULPxGWw3a/6+lMWLZnOTWtm+sO95RjLh90IUApGHysC0Q+M72/Sh7j0DWhU=,iv:sMYPW0vcjz5jG3RRuznGgJjoM5K+pQepXBCpHyEhNJA=,tag:KTvJseKBU4b9DlRjz3kmpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
