---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 1m
  dependsOn:
    - name: metallb
      namespace: networking
    - name: traefik
      namespace: networking
  upgrade:
    force: true
    remediation:
      retries: 3
  values:
    service:
      ui:
        type: LoadBalancer
        loadBalancerIP: ${SVC_LONGHORN_LB_IP}
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    defaultSettings:
      backupTarget: ${SECRET_SVC_LONGHORN_BACKUP_TARGET}
      backupTargetCredentialSecret: longhorn-backup-secrets
      defaultReplicaCount: 2
      taintToleration: "node-role.kubernetes.io/master=true:NoSchedule"
    ingress:
      enabled: false
    longhornManager:
      priorityClass: system-node-critical
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    longhornDriver:
      priorityClass: system-node-critical
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "2500m"
        memory: "500Mi"
