apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:f8kjuLF8bmJ3v+Mayj7AawYhiZwUnIIz6Go/3DiZBWhQ19X4bg==,iv:uNWcndfaMUjQ29V6iQDswnqNQsUlCsbCzlzKg6jas98=,tag:c9VatydFM4tI4XovFu99qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vaszxd76tm04yml3andpjshumnnzzugfhagw0l8q42cw3d8q3fs0vy6d0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV3U4Slg3SEk2RHdjM0Nk
            TStpNHd4NDJvYkFJUGFZdDNnWXFoa1VDUGpRCm5WeDB0VTY2QkNSV1paMEFtbnZS
            MXZseXJNOFN3bSt0TXpOamVPY0Zrck0KLS0tIDNFa2pmUmRjbm02cUJGcktBM0c5
            QU90enc3VVdtNThVcWo4azhLemlwSncKZIEcR4zVl7xgRsaKuxxIcGf1piPLzQ/7
            fCYu559zDLdC5+I4a57Ms1rcMcONqmotecy9X4IK6hIvLExAj2hK3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-22T08:50:50Z"
    mac: ENC[AES256_GCM,data:n+YtuWYIKdt3kGAbkPyGtR2UryY+PZcDAcCF/fCLca9cg+KPBhvNgLL1OdTTt7XQZIKjlMvsEmvgsupmRwS/MyiqM3lB1aBMEPB7Nt+/V3ip5CIVGXgHlmR35tR2HEBOjhUWF7zQ3+s0NfCsVqwbh/E9+FUWH3lBI0j5P3733F8=,iv:1uc7kx4dl4pBqNgbs62FbeKyZ4Cz39uRLqe42XW1XdA=,tag:d0PnOhzJ6tL+DezLkbooeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
