---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 15m
  maxHistory: 2
  timeout: 20m
  install:
    remediation:
      retries: 300
  upgrade:
    remediation:
      retries: 300
  dependsOn:
    - name: emqx
      namespace: home
    - name: home-assistant
      namespace: home
  values:
    initContainers:
      # npm-update:
      #   image: node:18-alpine
      #   command:
      #     - /bin/sh
      #     - -c
      #     - |
      #       if [[ -f /data/package.json ]]; then
      #           npm install --save $(npm outdated | cut -d' ' -f 1 | sed '1d' | xargs -I '$' echo '$@latest' | xargs echo);
      #       else
      #           echo "Skipping npm updates, no package.json found.";
      #       fi
      #   workingDir: /data
      #   volumeMounts:
      #     - name: config
      #       mountPath: /data
    image:
      repository: ghcr.io/k8s-at-home/node-red
      tag: v3.0.2
    env:
      TZ: "Europe/Rome"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"
    # Fix for https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/678
    # securityContext:
    #   runAsUser: 568
    #   runAsGroup: 568
    #   fsGroup: 568
    #   fsGroupChangePolicy: "OnRootMismatch"
    #   privileged: true
    ###
    persistence:
      config:
        enabled: true
        existingClaim: node-red-data
        mountPath: "/data"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SVC_NODERED_LB_IP}
        ports:
          http:
            port: 1880
