---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app node-red
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: node-red
      version: 13.0.3
      sourceRef:
        kind: HelmRepository
        name: truecharts-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: emqx
      namespace: home
    - name: home-assistant
      namespace: home
    - name: longhorn
      namespace: longhorn-system
  values:
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    env:
      TZ: "Europe/Rome"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SVC_NODERED_LB_IP}
        ports:
          main:
            port: 1880
            targetPort: 1880
    persistence:
      data:
        enabled: true
        mountPath: "/data"
        accessMode: ReadWriteOnce
        size: 5Gi
    portal:
      enabled: true
