---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: 3.8.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server-charts
        namespace: flux-system
      interval: 1m
  values:
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 1
        memory: 450Mi
