---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system.yaml
  - rook-ceph.yaml
  - system-upgrade.yaml
  - cert-manager.yaml
  - monitoring.yaml
  - node-feature-discovery.yaml
  - networking.yaml
  - longhorn-system.yaml
  - databases.yaml
  - home.yaml
